[package]
name = "nervo"
version = "0.1.0"
authors = ["VojtaKing"]
edition = "2021"
description = "easy to use TCP library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/VojtaKing/nervo"

